M48
; DRILL file {KiCad 7.0.1} date zo 26 mrt 2023 18:13:07 CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-26T18:13:07+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X5.6016Y-2.1815
X5.7984Y-2.1815
T2
X5.3Y-2.1
X5.3Y-4.2
X6.6Y-2.1
X6.6Y-4.2
T0
M30
